---
title: "Project 0 Code"
author: "Marshall Roll"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dpi = 300, fig.width = 7, fig.height = 5, warning = FALSE, echo = FALSE)
```

```{r}
# Raw data stored locally in folder called DataRaw
cort_data <- read_csv("../DataRaw/Project0_Clean_v2.csv")
```

```{r, include = FALSE}
library(tidyverse)
library(rmcorr)
library(naniar)
library(lme4)
library(lmerTest)
library(flextable)
library(ggridges)
library(table1)
library(gtsummary)
library(xfun)
library(multcomp)
```

# Cleaning

```{r}
# Rename variables and collect into working df
cort_final <- cort_data %>% mutate(
  date = `Collection Date`,
  sample = `Collection Sample`, 
  book_time = `Booket: Clock Time`,
  cap_time = `MEMs: Clock Time`,
  wake_time = `Sleep Diary reported wake time`,
  cortisol = `Cortisol (nmol/L)`,
  dhea = `DHEA (nmol/L)`
) %>% 
  dplyr::select(SubjectID, date, sample, book_time, cap_time, wake_time, cortisol, dhea)

# Carry wake time across all observations for calculation
cort_final <- cort_final %>% 
  group_by(SubjectID, date) %>% 
  mutate(wake_time = replace_na(wake_time, first(wake_time))) %>% 
  ungroup()

# Minutes since wake time for cap & booklet
cort_final <- cort_final %>% 
  mutate(wake_to_cap = as.numeric(cap_time - wake_time)/60,
         wake_to_book = as.numeric(book_time - wake_time)/60) 

# Replace cortisol levels greater than 80 nmol/L per investigator guidance
cort_final <- cort_final %>% 
  mutate(cortisol = ifelse(cortisol > 80, NA, cortisol))
```


# Table 1

```{r}
# Table 1 using gtsummary

tbl_comp <- cort_final %>% 
  group_by(sample) %>%
  mutate(
    is_complete = ifelse(!is.na(wake_to_cap) & !is.na(wake_to_book), TRUE, FALSE),
    is_complete_cap = ifelse(!is.na(wake_to_cap), TRUE, FALSE),
    is_complete_book = ifelse(!is.na(wake_to_book), TRUE, FALSE)
  ) %>% 
  ungroup() %>% 
  tbl_summary(
    include = c(is_complete_book, is_complete_cap, is_complete),
    statistic = all_categorical() ~ "{n} ({p}%)",
    label = list(
      is_complete = "Complete",
      is_complete_cap = "Complete Cap",
      is_complete_book = "Complete Booklet"
    ),
    missing_text = "(Missing)"
  )
  
tbl_by_sample <- cort_final %>% 
  mutate(time = case_when(
      sample == 2 ~ 30,
      sample == 4 ~ 600, 
      TRUE ~ NA
    ), 
    good_ad = !is.na(wake_to_book) & 
      abs(wake_to_book - time) <= 7.5,
    adequate_ad = !is.na(wake_to_book) & 
      abs(wake_to_book - time) <= 15

  ) %>% 
  tbl_summary(
  by = sample, 
  include = c(wake_to_book, wake_to_cap, cortisol, dhea, 
              good_ad, adequate_ad),
   statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} ({p}%)"
    ),
    digits = all_continuous() ~ 2,
    label = list(wake_to_book = "Wake to Booklet Time (Minutes)",
                 wake_to_cap = "Wake to Cap Time (Minutes)",
                 cortisol = "Cortisol (nmol/L)",
                 dhea = "DHEA (nmol/L)",
                 good_ad = "Good Adherence (7.5 min)",
                 adequate_ad = "Adequate Adherence (15 min)"),
    missing_text = "(Missing)"
  ) 

tbl_final <-
  tbl_merge(
    tbls = list(tbl_by_sample, tbl_comp),
    tab_spanner = c("By Sample", "Total")
  )

tbl_final
```

# Missingness Evaluation
```{r}
# Visualize missingness of variables by sample
# Cap time missing more than book time
gg_miss_var(cort_final, facet = sample)


# Exploratory missingness plots
# Few missing values of cortisol and DHEA, can rule out MNAR
# Missingness seems to be ignorable
# cort_final %>% 
#   bind_shadow() %>%
#   ggplot(aes(x = wake_to_book,
#                fill = cortisol_NA)) +
#   geom_histogram()
# 
# cort_final %>%
#   bind_shadow() %>%
#   ggplot(aes(x = cortisol,
#                fill = wake_to_book_NA)) +
#   geom_histogram()
# 
# cort_final %>% 
#   bind_shadow() %>%
#   ggplot(aes(x = wake_to_book,
#                fill = wake_to_cap_NA)) +
#   geom_histogram()
```



# RQ1 - Cap & Book Time Agreement
```{r}
# Repeated measures correlation - only takes into account complete cases
# Also only measures correlation within subjects -- does not alert to systematic biases
rep_corr <- rmcorr(participant = factor(SubjectID), 
                 measure1 = wake_to_book, 
                 measure2 = wake_to_cap,
                 dataset = cort_final)

rep_corr

# R = 0.99

# Mixed model for assessing correlation with random intercept for subject
# Shows a moderate ~10 min difference between average cap and book time from wake 
corr_glmm <- lmer(wake_to_cap ~ wake_to_book + (1 | SubjectID), 
              data = cort_final)

summary(corr_glmm)

# Pretty good agreement, going to use book time because there is less missingness going forward

# Predictions for plot for agreement
agree_pred <- data.frame(
    wake_to_book = seq(
      min(cort_final$wake_to_book, na.rm = TRUE),
      max(cort_final$wake_to_book, na.rm = TRUE),
      length.out = 200
    )
  )

agree_pred$pred <- predict(
  corr_glmm,
  newdata = agree_pred,
  re.form = NA
)

# Subject-specific correlation measures visualization
cort_final %>% 
  ggplot() + 
  geom_point(aes(x = wake_to_book, y = wake_to_cap, 
                 color = factor(SubjectID), 
                 group = factor(SubjectID)),
             alpha = 0.25) + 
  geom_line(aes(x = wake_to_book, y = wake_to_cap, 
                 color = factor(SubjectID), 
                 group = factor(SubjectID)),
            stat = "smooth", method = 'lm', 
            se = FALSE, alpha = 0.25, linewidth = 0.8) +
   geom_line(
    data = agree_pred,
    aes(x = wake_to_book, y = pred),
    color = "black",
    linewidth = 1.25
  ) + 
  scale_color_viridis_d(option = "H") + 
  theme_minimal() +
  guides(color = "none") + 
  labs(x = "Minutes Since Wake (Booklet)", y = "Minutes Since Wake (Cap)")
 
# Proportion of missingness across time points
# Between 20-30% for all time pts.
# Incorporated into table1
# cort_final %>%
#   group_by(sample) %>%
#   summarise(
#     n_total = n(),
#     pct_complete = round(sum(!is.na(wake_to_cap) & !is.na(wake_to_book)) / n_total * 100, 1),
#     pct_complete_cap = round(sum(!is.na(wake_to_cap))/n() * 100, 1),
#     pct_complete_book = round(sum(!is.na(wake_to_book))/n() * 100, 1)
#   ) %>% 
#   flextable() %>% 
#   set_header_labels(sample = "Sample",
#                     n_total = "n",
#                     pct_complete = "Complete (%)", 
#                     pct_complete_cap = "Complete Cap (%)",
#                     pct_complete_book = "Complete Book (%)")
```

# RQ2: Adherence to Timing Schedule

```{r}
# Want to test adherence in second sample (how close to 30 mins) and final sample (how close to 600)
# Adequate: within 15 mins, Good: within 7.5 minutes

# Sample 2
cort_samp2 <- cort_final %>% filter(sample == 2)

cort_samp2 <- cort_samp2 %>% 
  mutate(within_7.5 = ifelse(wake_to_book > 23 & wake_to_book < 37, 1, 0),
         within_15 = ifelse(wake_to_book > 15 & wake_to_book < 45, 1, 0))

cort_samp2 %>% summarize(
  prop_7.5 = round(sum(within_7.5, na.rm = TRUE)/n() * 100, 1),
  prop_15 = round(sum(within_15, na.rm = TRUE)/n() * 100, 1)
)

# Sample 4
cort_samp4 <- cort_final %>% filter(sample == 4)

cort_samp4 <- cort_samp4 %>% 
  mutate(within_7.5 = ifelse(wake_to_book > 593 & wake_to_book < 607, 1, 0),
         within_15 = ifelse(wake_to_book > 585 & wake_to_book < 615, 1, 0))

cort_samp4 %>% summarize(
  prop_7.5 = round(sum(within_7.5, na.rm = TRUE)/n() * 100, 1),
  prop_15 = round(sum(within_15, na.rm = TRUE)/n() * 100, 1)
)

# Adherence for 600 minutes is low (35.5% within 15 minutes)
# Density plot to assess full distribution

cort_final %>%
  mutate(sample = factor(sample, 
                         levels = c(4, 3, 2, 1),
                         labels = c("Sample 4 (+600 minutes)", 
                                   "Sample 3 (Lunchtime)",
                                   "Sample 2 (+30 minutes)",
                                   "Sample 1 (Wake time)"))) %>% 
  ggplot(aes(x = wake_to_book, y = sample, fill = sample)) + 
  geom_density_ridges(alpha = 0.7, scale = 0.9) +
  scale_fill_manual(values = c("lightgreen", "#e6194B", "#f58231", "#4363d8")) +
  theme_minimal() +
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_blank()
  ) +
  labs(x = "Minutes Since Wake (Booklet)", 
       y = NULL)

```

# RQ3: Cortisol & DHEA analysis

```{r}
# Fit 2 Mixed effects models with random intercepts - DHEA and cortisol as outcomes
cort_final <- cort_final %>% 
  mutate(wake_30 = pmax(wake_to_book - 30, 0))

cort_mod <- lmer(log(cortisol) ~  wake_to_book + wake_30 + (1|SubjectID), data = cort_final)

summary(cort_mod)
# Exponentiated estimates of pre-30 minute effect (beta1) and post-30 minute effect (beta1 + beta2)
cort_coefs <- c(fixef(cort_mod)[2], fixef(cort_mod)[2] + fixef(cort_mod)[3])
names(cort_coefs) <- c("pre30", "post30")

dhea_mod <- lmer(log(dhea) ~  wake_to_book + wake_30 + (1|SubjectID), data = cort_final)

summary(dhea_mod)
# Exponentiated estimates of pre-30 minute effect (beta1) and post-30 minute effect (beta1 + beta2)
dhea_coefs <- c(fixef(dhea_mod)[2], fixef(dhea_mod)[2] + fixef(dhea_mod)[3])
names(dhea_coefs) <- c("pre30", "post30")
```

```{r}
# Function to calculate confidence intervals and p-values
piecewise_linear_results <- function(
  fit,
  scale_minutes = 1,
  digits = 2
) {

  # Contrast matrix
  # After 30 min set as sum of beta1 and beta2
  K <- rbind(
    "Before 30 min" = c(0, 1, 0),
    "After 30 min"  = c(0, 1, 1)
  )

  # Scale contrasts (eg, 30 minute effects)
  K_scaled <- scale_minutes * K

  glht_fit <- glht(fit, linfct = K_scaled)
  summ <- summary(glht_fit)
  ci <- confint(glht_fit)

  # Convert to percent change
  est <- exp(summ$test$coefficients)
  ci_lb <- exp(ci$confint[, "lwr"])
  ci_ub <- exp(ci$confint[, "upr"])
  ci_lower <- round((ci_lb - 1) * 100, digits)
  ci_upper <- round((ci_ub - 1) * 100, digits)

  result_df <- data.frame(
    eff = rownames(K),
    pct_change = (est - 1) * 100,
    ci = paste0("(", ci_lower, ", ", ci_upper, ")"),
    p_val = summ$test$pvalues
  ) %>% 
    mutate(
      across(
        c(pct_change),
        ~ round(.x, digits)
      ),
      p_val = ifelse(p_val < 0.001, "<0.001",
                         round(p_val, 3))
    )

  # Generate flextable
  flextable(result_df) %>% 
    autofit() %>% 
    align(j = -1, align = "center", part = "all") %>% 
    bold(part = "header") %>% 
    set_header_labels(eff = "Effect",
                    pct_change = "Percent Change/30 min",
                    ci = "95% CI", 
                    p_val = "p-value")
    
}

piecewise_linear_results(cort_mod, 30) 
piecewise_linear_results(dhea_mod, 30) 
```


```{r}
# Predictions and plot with predicted line for cortisol
cort_pred <- data.frame(
    wake_to_book = seq(
      min(cort_final$wake_to_book, na.rm = TRUE),
      max(cort_final$wake_to_book, na.rm = TRUE),
      length.out = 200
    )
  ) %>% 
  mutate(wake_30 = pmax(0, wake_to_book - 30))

cort_pred$pred <- predict(
  cort_mod,
  newdata = cort_pred,
  re.form = NA
)

# Standard errors for plotting
X_cort <- model.matrix(
  ~ wake_to_book + wake_30,
  data = cort_pred
)
V_cort <- vcov(cort_mod)
cort_pred$se_log <- sqrt(diag(X_cort %*% V_cort %*% t(X_cort)))
cort_pred <- cort_pred %>%
  mutate(
    lower = exp(pred - 1.96 * se_log),
    upper = exp(pred + 1.96 * se_log)
  )

# Cortisol plot with ribbon for population-average model CI's
cort_final %>%
  ggplot() +
  geom_point(
    data = cort_final, 
    aes(x = wake_to_book, y = cortisol),
    color = "darkslategray", alpha = 0.3
    ) +
  geom_ribbon(
    data = cort_pred,
    aes(
      x = wake_to_book,
      ymin = lower,
      ymax = upper
    ),
    alpha = 0.25
  ) +
  geom_line(
    data = cort_pred,
    aes(x = wake_to_book, y = exp(pred)),
    color = "tomato2",
    linewidth = 1.2
  ) +
  scale_color_viridis_d(option = "H") +
  theme_minimal() +
  guides(color = "none") +
  labs(x = "Minutes Since Wake (Booklet)", y = "Cortisol nmol/L")

# Predictions and plot with predicted line for DHEA
dhea_pred <- data.frame(
    wake_to_book = seq(
      min(cort_final$wake_to_book, na.rm = TRUE),
      max(cort_final$wake_to_book, na.rm = TRUE),
      length.out = 200
    )
  ) %>% 
  mutate(wake_30 = pmax(0, wake_to_book - 30))

dhea_pred$pred <- predict(
  dhea_mod,
  newdata = dhea_pred,
  re.form = NA
)

#Standard errors for plotting
X_dhea <- model.matrix(
  ~ wake_to_book + wake_30,
  data = dhea_pred
)

V_dhea <- vcov(dhea_mod)
dhea_pred$se_log <- sqrt(diag(X_dhea %*% V_dhea %*% t(X_dhea)))
dhea_pred <- dhea_pred %>%
  mutate(
    lower = exp(pred - 1.96 * se_log),
    upper = exp(pred + 1.96 * se_log)
  )

# DHEA plot with ribbon for population-average model CI's
cort_final %>%
  ggplot() +
  geom_point(
    color = "darkslategray", 
    aes(x = wake_to_book, y = dhea),
    alpha = 0.4) +
  geom_ribbon(
    data = dhea_pred,
    aes(
      x = wake_to_book,
      ymin = lower,
      ymax = upper
    ),
    alpha = 0.25
  ) +
  geom_line(
    data = dhea_pred,
    aes(x = wake_to_book, y = exp(pred)),
    color = "steelblue2",
    linewidth = 1.2
  ) +
  scale_color_viridis_d(option = "A") +
  theme_minimal() +
  guides(color = "none") +
  labs(x = "Minutes Since Wake (Booklet)", y = "DHEA nmol/L")

```

```{r}
sessionInfo()
```

