---
title: "Project 2 Preliminary Analysis"
author: "Marshall Roll"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
---

```{r}
library(tidyverse)
library(powertools)
library(pwr)
library(flextable)
```

```{r}
# Raw data stored locally in Documents\Advanced_Methods_Roll\Project 1\Code
prelim <- read_csv("../DataRaw/PrelimData.csv")
```

```{r}
cor(prelim)
# use 0.26 - 0.68 as range of correlation in R
```

```{r}
# Omnibus tests
full_cvlt_mod <- lm(CVLT_CNG3 ~ IL_6 + MCP_1, data = prelim)
summary(full_cvlt_mod) # p = 0.198

full_cort_mod <- lm(CORT_CNG3 ~ IL_6 + MCP_1, data = prelim)
summary(full_cort_mod) # p = 0.00014

# Individual tests for cort model
cort_mod_il6 <- lm(CORT_CNG3 ~ IL_6 , data = prelim)
summary(cort_mod_il6) # p < 0.001

cort_mod_mcp1 <- lm(CORT_CNG3 ~ MCP_1 , data = prelim)
summary(cort_mod_mcp1) # p < 0.001
```


# Aim 1 Power

```{r}
omnibus_power_sweep <- function(n = 175, p = 4, alpha = 0.025,
                        r_range = seq(0.20, 0.50, by = 0.05)){
  
  results <- data.frame()
  
  for(r in r_range){
    
    pwr <- mlrF.overall(N = n, p = p, Rsq = r^2, alpha = alpha)
    results <- rbind(results, data.frame(
        r = r,
        pwr = pwr
    ))
  }
  return(results)
}

omni <- omnibus_power_sweep()
```

```{r}
individ_power_sweep <- function(n = 175, alpha = 0.025,
                        r_range = seq(0.20, 0.50, by = 0.05)){
  
  results <- data.frame()
  
  for(r in r_range){
    
    pwr <- corr.1samp(N = n, rhoA = r, alpha = alpha)
    results <- rbind(results, data.frame(
        r = r,
        pwr = pwr
    ))
  }
  return(results)
}

individ <- individ_power_sweep()
```


```{r}
omni <- omni %>% 
  mutate(Test = "Omnibus")

individ <- individ %>% 
  mutate(Test = "Individual")

overall_res <- rbind(omni, individ)

overall_res <- overall_res %>%
  pivot_wider(
    names_from = Test,
    values_from = pwr
  ) %>% 
  mutate(eff_pwr = Omnibus * Individual)

overall_res %>%
  flextable() %>%
  set_header_labels(
    r = "Effect Size (r)",
    Omnibus = "Omnibus F-Test Power",
    Individual = "Theoretical Individual Power",
    eff_pwr = "Protected Individual Power*"
  ) %>%
  colformat_double(digits = 3) %>%
  add_footer_lines("*Note: Protected Power is the joint probability of both Omnibus and Individual significance.") %>%
  autofit() %>%
  theme_booktabs()
```


```{r}
delta_vals <- c(0.3, 0.4, 0.5) 

interaction_power_sweep <- function(n_total = 175, alpha = 0.025,
                        r_range = seq(0.25, 0.75, by = 0.05),
                        n_am_pos = c(50, 75, 100, 125)){
  
  results <- data.frame()
  
  for (n in n_am_pos){
    n_am_neg = n_total - n
    n_ratio = n_am_neg / n # n2/n1 n1: amyloid pos, n2: amyloid neg
    
    for(r in r_range){
      for(delta in delta_vals){
        
        # r: correlation between amyloid pos and outcome
        # r2: correlation between amyloid neg and outcome
        r2 <- r - delta 
        
        if(r2 >= 0.99) next
        
        pwr <- corr.2samp(
          n1 = n,
          n.ratio = n_ratio,
          rho1 = r,
          rho2 = r2,
          alpha = alpha,
          sides = 2
        )
        
        results <- rbind(results, data.frame(
          n_am_pos = n,
          n_am_neg = n_am_neg,
          r = r,
          delta = delta,
          r2 = r2,
          power = pwr
        ))
      }
    }
  }
  return(results)
}

interaction_res <- interaction_power_sweep()

interaction_res %>% 
  mutate(delta = case_when(
    delta == 0.3 ~ "0.3 (Small)",
    delta == 0.4 ~ "0.4 (Moderate)",
    delta == 0.5 ~ "0.5 (Large)"
  )) %>% 
  ggplot(aes(x = r, y = power, group = n_am_pos, color = factor(n_am_pos))) +
  geom_line() + 
  facet_grid(~delta) + 
  geom_hline(yintercept = 0.8, linetype = "dashed", color = "red") + 
  theme_minimal() + 
  labs(x = "Amlyoid Positive Effect Size (Correlation)", y = "Power", color = "Number Amyloid\nPositive Patients",
       title = "Predicted Power by Interaction Effect Size")

# Correlation represents strength of association between predictor and outcome
# Effect size represents a difference in strength of association between amyloid positive and amyloid negative patients (0.1 = small difference, 0.3 = large difference)
```
